#pragma once

#include <stddef.h>
#include <stdint.h>

#include "driver/gpio.h"
#include "esp_adc/adc_oneshot.h"

#define FUNKEY_LOG_TAG "funkey_shifter"

#define FUNKEY_USB_VID 0x0E4C
#define FUNKEY_USB_PID 0x7288
#define FUNKEY_BCD_DEVICE 0x0100

#define FUNKEY_REPORT_LEN 8
#define FUNKEY_PORTAL_PACKET_LEN 7
#define FUNKEY_PORTAL_DESC_LEN (9 + 7)

#define FUNKEY_ITF_PORTAL 0
#define FUNKEY_ITF_TOTAL 1

#define FUNKEY_EP_PORTAL_IN 0x81

#define FUNKEY_REQ_INIT 0x00
#define FUNKEY_REQ_GET_REPORT 0x01
#define FUNKEY_REQ_SET_REPORT 0x02
#define FUNKEY_REQ_REMOVE 0x03
#define FUNKEY_REQ_SET_RAW_PACKET 0x04
#define FUNKEY_REQ_GET_BLE_STATUS 0x05
#define FUNKEY_REQ_GET_CAPABILITIES 0x06

#define FUNKEY_BLE_NAME "FunkeyShifter"
#define FUNKEY_BLE_CMD_SET_REPORT 0x02
#define FUNKEY_BLE_CMD_REMOVE 0x03
#define FUNKEY_BLE_CMD_USE_PHYSICAL 0x04
#define FUNKEY_BLE_STATUS_LEN 8

#define FUNKEY_CAPABILITIES_LEN 8
#define FUNKEY_CAP_VERSION 0x01
#define FUNKEY_CAP_MANAGED_CATALOG 0x01
#define FUNKEY_CAP_BLE_CONTROL 0x02
#define FUNKEY_CAP_RAW_PACKET_SET 0x04
#define FUNKEY_CAP_PHYSICAL_READER 0x08

#ifndef FUNKEY_PHYSICAL_ENABLED
#define FUNKEY_PHYSICAL_ENABLED 1
#endif

#if FUNKEY_PHYSICAL_ENABLED
// Physical reader wiring:
//   pad 1/common -> GND
//   pad 2/R4 checksum -> ADC GPIO below, with selected pull-up to 3.3V
//   pad 3/R1 ones     -> ADC GPIO below, with selected pull-up to 3.3V
//   pad 4/R2 tens     -> ADC GPIO below, with selected pull-up to 3.3V
//   pad 5/R3 hundreds -> ADC GPIO below, with selected pull-up to 3.3V
//
// Default mapping uses the adjacent GPIO8..GPIO11 header block:
//   GPIO8  = ADC1 channel 7
//   GPIO9  = ADC1 channel 8
//   GPIO10 = ADC1 channel 9
//   GPIO11 = ADC2 channel 0
#ifndef FUNKEY_PHYSICAL_PAD2_R4_GPIO
#define FUNKEY_PHYSICAL_PAD2_R4_GPIO GPIO_NUM_8
#endif
#ifndef FUNKEY_PHYSICAL_PAD2_R4_ADC_UNIT
#define FUNKEY_PHYSICAL_PAD2_R4_ADC_UNIT ADC_UNIT_1
#endif
#ifndef FUNKEY_PHYSICAL_PAD2_R4_ADC_CHANNEL
#define FUNKEY_PHYSICAL_PAD2_R4_ADC_CHANNEL ADC_CHANNEL_7
#endif
#ifndef FUNKEY_PHYSICAL_PAD3_R1_GPIO
#define FUNKEY_PHYSICAL_PAD3_R1_GPIO GPIO_NUM_9
#endif
#ifndef FUNKEY_PHYSICAL_PAD3_R1_ADC_UNIT
#define FUNKEY_PHYSICAL_PAD3_R1_ADC_UNIT ADC_UNIT_1
#endif
#ifndef FUNKEY_PHYSICAL_PAD3_R1_ADC_CHANNEL
#define FUNKEY_PHYSICAL_PAD3_R1_ADC_CHANNEL ADC_CHANNEL_8
#endif
#ifndef FUNKEY_PHYSICAL_PAD4_R2_GPIO
#define FUNKEY_PHYSICAL_PAD4_R2_GPIO GPIO_NUM_10
#endif
#ifndef FUNKEY_PHYSICAL_PAD4_R2_ADC_UNIT
#define FUNKEY_PHYSICAL_PAD4_R2_ADC_UNIT ADC_UNIT_1
#endif
#ifndef FUNKEY_PHYSICAL_PAD4_R2_ADC_CHANNEL
#define FUNKEY_PHYSICAL_PAD4_R2_ADC_CHANNEL ADC_CHANNEL_9
#endif
#ifndef FUNKEY_PHYSICAL_PAD5_R3_GPIO
#define FUNKEY_PHYSICAL_PAD5_R3_GPIO GPIO_NUM_11
#endif
#ifndef FUNKEY_PHYSICAL_PAD5_R3_ADC_UNIT
#define FUNKEY_PHYSICAL_PAD5_R3_ADC_UNIT ADC_UNIT_2
#endif
#ifndef FUNKEY_PHYSICAL_PAD5_R3_ADC_CHANNEL
#define FUNKEY_PHYSICAL_PAD5_R3_ADC_CHANNEL ADC_CHANNEL_0
#endif
#ifndef FUNKEY_PHYSICAL_USE_INTERNAL_PULLUPS
#define FUNKEY_PHYSICAL_USE_INTERNAL_PULLUPS 0
#endif
#ifndef FUNKEY_PHYSICAL_EXTERNAL_PULLUP_OHMS
#define FUNKEY_PHYSICAL_EXTERNAL_PULLUP_OHMS 220000U
#endif
#ifndef FUNKEY_PHYSICAL_INTERNAL_PULLUP_OHMS
#define FUNKEY_PHYSICAL_INTERNAL_PULLUP_OHMS 27000U
#endif
#ifndef FUNKEY_PHYSICAL_PULLUP_OHMS
#if FUNKEY_PHYSICAL_USE_INTERNAL_PULLUPS
#define FUNKEY_PHYSICAL_PULLUP_OHMS FUNKEY_PHYSICAL_INTERNAL_PULLUP_OHMS
#else
#define FUNKEY_PHYSICAL_PULLUP_OHMS FUNKEY_PHYSICAL_EXTERNAL_PULLUP_OHMS
#endif
#endif
#ifndef FUNKEY_PHYSICAL_ADC_FULL_SCALE_RAW
#define FUNKEY_PHYSICAL_ADC_FULL_SCALE_RAW 4095U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_TARGET_SCALE_NUM
#define FUNKEY_PHYSICAL_ADC_TARGET_SCALE_NUM 900U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_TARGET_SCALE_DEN
#define FUNKEY_PHYSICAL_ADC_TARGET_SCALE_DEN 1000U
#endif
#ifndef FUNKEY_PHYSICAL_MAX_BUCKET_DELTA_RAW
#define FUNKEY_PHYSICAL_MAX_BUCKET_DELTA_RAW 300U
#endif
#ifndef FUNKEY_PHYSICAL_SAMPLE_COUNT
#define FUNKEY_PHYSICAL_SAMPLE_COUNT 8U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_SETTLE_DELTA_RAW
#define FUNKEY_PHYSICAL_ADC_SETTLE_DELTA_RAW 4U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_SETTLE_READS
#define FUNKEY_PHYSICAL_ADC_SETTLE_READS 4U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_SETTLE_TIMEOUT_MS
#define FUNKEY_PHYSICAL_ADC_SETTLE_TIMEOUT_MS 750U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_SETTLE_DELAY_MS
#define FUNKEY_PHYSICAL_ADC_SETTLE_DELAY_MS 5U
#endif
#ifndef FUNKEY_PHYSICAL_SAMPLE_DELAY_MS
#define FUNKEY_PHYSICAL_SAMPLE_DELAY_MS 2U
#endif
#ifndef FUNKEY_PHYSICAL_POLL_MS
#define FUNKEY_PHYSICAL_POLL_MS 50U
#endif
#ifndef FUNKEY_PHYSICAL_STABLE_POLLS
#define FUNKEY_PHYSICAL_STABLE_POLLS 4U
#endif
#ifndef FUNKEY_PHYSICAL_ADC_ATTEN
#define FUNKEY_PHYSICAL_ADC_ATTEN ADC_ATTEN_DB_12
#endif
#endif

#ifndef FUNKEY_FLASH_HOTKEY_ENABLED
#define FUNKEY_FLASH_HOTKEY_ENABLED 1
#endif
#ifndef FUNKEY_FLASH_HOTKEY_GPIO
#if FUNKEY_PHYSICAL_ENABLED
#define FUNKEY_FLASH_HOTKEY_GPIO FUNKEY_PHYSICAL_PAD2_R4_GPIO
#else
#define FUNKEY_FLASH_HOTKEY_GPIO GPIO_NUM_8
#endif
#endif
#ifndef FUNKEY_FLASH_HOTKEY_HOLD_MS
#define FUNKEY_FLASH_HOTKEY_HOLD_MS 250U
#endif
#ifndef FUNKEY_FLASH_HOTKEY_SAMPLE_MS
#define FUNKEY_FLASH_HOTKEY_SAMPLE_MS 10U
#endif
#ifndef FUNKEY_FLASH_HOTKEY_ADC_MAX_RAW
#define FUNKEY_FLASH_HOTKEY_ADC_MAX_RAW 8U
#endif
#ifndef FUNKEY_FLASH_HOTKEY_ADC_SAMPLE_COUNT
#define FUNKEY_FLASH_HOTKEY_ADC_SAMPLE_COUNT 4U
#endif
#ifndef FUNKEY_FLASH_HOTKEY_ADC_ATTEN
#if FUNKEY_PHYSICAL_ENABLED
#define FUNKEY_FLASH_HOTKEY_ADC_ATTEN FUNKEY_PHYSICAL_ADC_ATTEN
#else
#define FUNKEY_FLASH_HOTKEY_ADC_ATTEN ADC_ATTEN_DB_12
#endif
#endif

namespace funkey::protocol {

const uint8_t *capabilitiesResponse();
size_t capabilitiesResponseLen();

} // namespace funkey::protocol
